name: Auto Sync
on:
  schedule:
    - cron: '*/5 * * * *' # Chạy mỗi 5 phút
  push:
    branches: [ main ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      - name: Sync changes
        run: |
          bash sync.sh